name: Go Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  GOVERSION: 1.22.x
  GOLANGCI_LINT_VERSION: v1.61.0
  PR_COMMIT_SHA: ${{ github.event.client_payload.pull_request.head.sha }}
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        lfs: true
        persist-credentials: false
        ref: ${{ env.PR_COMMIT_SHA }}
    - name: Install Go
      uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
      with:
        go-version: ${{ env.GOVERSION }}
        cache-dependency-path: "**/*.sum"
    - name: Disarm go:embed directives to enable linters that compile source code
      run: git grep -l 'go:embed' -- provider | xargs --no-run-if-empty sed -i
        's/go:embed/ goembed/g'
    - name: golangci-lint
      uses: golangci/golangci-lint-action@971e284b6050e8a5849b72094c50ab08da042db8 # v6.1.1
      with:
        version: ${{ env.GOLANGCI_LINT_VERSION }}
        args: -c .golangci.yml -v --color always 
    name: lint
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

    - name: Set up Go
      uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5
      with:
        go-version: '1.22'
        cache: true

    - name: Install dependencies
      run: |
        go mod download
        go get github.com/stretchr/testify

    - name: Run tests
      run: go test -count=1 -cover -timeout 2h -parallel 4 ./... -v

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4
      with:
        name: test-results
        path: |
          **/*_test.go
        retention-days: 7